### ISSUE TITLE
Clean stack traces

### ISSUE THREAD

**Issue by remcohaszing** [unifiedjs/unified-language-server#50]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

If a plugin throws, an error diagnostic is created. This diagnostic contains the stack trace as the message.

### Solution

It might look a bit nicer to clean the stack trace using [`clean-stack`](https://github.com/sindresorhus/clean-stack), or to trim out even unified internals, which requires [`stack-utils`](https://github.com/tapjs/stack-utils).

### Alternatives

Don’t trim stack traces. :shrug:

**Comment by wooorm** [comment]
My main problem with these things is that when they don’t work, it becomes really really hard to debug things
Sometimes, there are problems in this project, or in unified itself.

Do you have an example of an overlong trace and how you hope to clean it?

**Comment by remcohaszing** [comment]
I created the following `.remarkrc.js` for testing purposes:

```js
export default {
  plugins: [
    './my-plugin.js'
  ]
}
```

and `my-plugin.js`:

```js
export default function myPlugin() {
  return () => {
    throw new Error('Oh noez!')
  }
}
```

This yields the following diagnostic:

```
Error: Oh noez!
    at file:///home/remco/Projects/example/my-plugin.js:3:11
    at wrapped (file:///home/remco/Projects/example/node_modules/trough/index.js:115:27)
    at next (file:///home/remco/Projects/example/node_modules/trough/index.js:65:23)
    at Object.run (file:///home/remco/Projects/example/node_modules/trough/index.js:36:5)
    at executor (file:///home/remco/Projects/example/node_modules/unified/lib/index.js:321:20)
    at Function.run (file:///home/remco/Projects/example/node_modules/unified/lib/index.js:312:5)
    at OF (/home/remco/.vscode/extensions/unifiedjs.vscode-remark-2.0.0/out/remark-language-server.js:205:364)
    at n (/home/remco/.vscode/extensions/unifiedjs.vscode-remark-2.0.0/out/remark-language-server.js:200:11651)
    at a (/home/remco/.vscode/extensions/unifiedjs.vscode-remark-2.0.0/out/remark-language-server.js:200:11406)
    at i (/home/remco/.vscode/extensions/unifiedjs.vscode-remark-2.0.0/out/remark-language-server.js:200:11805)
```

I think it looks slightly nicer with relative paths

```
Error: Oh noez!
    at my-plugin.js:3:11
    at wrapped (node_modules/trough/index.js:115:27)
    at next (node_modules/trough/index.js:65:23)
    at Object.run (node_modules/trough/index.js:36:5)
    at executor (node_modules/unified/lib/index.js:321:20)
    at Function.run (node_modules/unified/lib/index.js:312:5)
    at OF (~/.vscode/extensions/unifiedjs.vscode-remark-2.0.0/out/remark-language-server.js:205:364)
    at n (~/.vscode/extensions/unifiedjs.vscode-remark-2.0.0/out/remark-language-server.js:200:11651)
    at a (~/.vscode/extensions/unifiedjs.vscode-remark-2.0.0/out/remark-language-server.js:200:11406)
    at i (~/.vscode/extensions/unifiedjs.vscode-remark-2.0.0/out/remark-language-server.js:200:11805)
```

And this is what it would look like with trimmed unified internals:

```
Error: Oh noez!
    at my-plugin.js:3:11
```

For every plugin that runs before the one throwing an error, the following lines are repeated:

```
    at wrapped (file:///home/remco/Projects/example/node_modules/trough/index.js:115:27)
    at next (file:///home/remco/Projects/example/node_modules/trough/index.js:65:23)
    at done (file:///home/remco/Projects/example/node_modules/trough/index.js:148:7)
    at then (file:///home/remco/Projects/example/node_modules/trough/index.js:158:5)
```

I also found out the stack trace is apparently capped at 10 lines, so it’s not getting worse than the examples shown here.

**Comment by wooorm** [comment]
I find that info rather useful, I don‘t get why we should strip useful information about crashes.

Why not use a vfile-message if you want pretty warnings?

**Comment by remcohaszing** [comment]
This was just an idea I have no strong feelings about. If you don’t like it, lets keep it as-is. :)
